version: '3'

services:
  postgres:
    container_name: nidz-db
    image: postgres:16
    volumes:
      - ../src/main/resources/db/global:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=nidz-db
      - POSTGRES_USER=nidz
      - POSTGRES_PASSWORD=nidz
    ports:
      - "5432:5432"
    networks:
      - nidz-network

networks:
  nidz-network:
    driver: bridge
